# Generated by Django 4.1.1 on 2022-10-24 10:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя автора')),
                ('cover', models.ImageField(blank=True, upload_to='covers/%Y/%m/%d', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Oписание атора')),
                ('choice', models.CharField(choices=[('a', ' Автор просто суппер'), ('b', 'Автор средний'), ('c', 'Автор ужастный')], max_length=1)),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID-UUID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('language', models.CharField(choices=[('a', 'ru'), ('b', 'en'), ('c', 'other')], db_index=True, max_length=1, verbose_name='Язык')),
                ('description', models.TextField(blank=True, verbose_name='Текст описания')),
                ('files', models.FileField(blank=True, upload_to='book/%Y/%m/%d', verbose_name='Файлы книг')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ценна')),
                ('cover', models.ImageField(blank=True, upload_to='covers/%Y/%m/%d', verbose_name='Изображение')),
                ('come_out', models.IntegerField(blank=True, null=1932, verbose_name='Год выхода')),
                ('edition', models.CharField(blank=True, max_length=200, verbose_name='Издание')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'permissions': [('special_status', 'Can read all books')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=255)),
                ('date_posted', models.DateTimeField(auto_now_add=True, null=2008)),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии',
                'ordering': ['-date_posted'],
            },
        ),
    ]
